$(document).ready(function(){
    $("#Connexion").click(function(){
        $("#Connexion_modal").modal();
    });
});
$(document).ready(function(){
    $("#Inscription").click(function(){
        $("#Inscription_modal").modal();
    });
});
